### ISSUE TITLE
libcamera-vid not showing video

### ISSUE THREAD

**Issue by pbaetens** [raspberrypi/libcamera#24] opened 2022-08-24 12:05 UTC
libcamera-vid does not show video, except when used with the --qt-preview argument - then everything is OK.
tested with latest master.
with a checkout from April, this was still working fine.

**Comment by 6by9** [comment] 2022-08-24 12:36
Duplicate of https://github.com/raspberrypi/libcamera-apps/issues/347

**Closed by 6by9** 2022-08-24 12:36 UTC
